name: Release with goreleaser

on:
  push:
    # Create release for `v1.2.3` tags.
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12

      - name: pwd
        run: tree

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.1.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}